@host=https://localhost:7086
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Guilherme",
    "lastName": "Felipe",
    "email": "guilherme-silva@estudante.sc.senai",
    "password": "123456"
}